# Generated by Django 5.2.7 on 2025-10-08 04:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('surname', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('passport_number', models.CharField(max_length=12, verbose_name='Номер паспорта')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Номер телефона')),
                ('email', models.CharField(max_length=100, verbose_name='Эл.почта')),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя отеля')),
                ('address', models.CharField(max_length=100, verbose_name='Адрес отеля')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Номер телефона')),
                ('email', models.CharField(max_length=100, verbose_name='Эл.почта')),
                ('description', models.TextField(verbose_name='Описание отеля')),
            ],
        ),
        migrations.CreateModel(
            name='Room_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Тип комнаты')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateTimeField(verbose_name='Дата и время бронирования')),
                ('check_in_date', models.DateField(verbose_name='Дата заезда')),
                ('check_out_date', models.DateField(verbose_name='Дата выезда')),
                ('number_of_guests', models.IntegerField(verbose_name='Количество гостей')),
                ('status', models.CharField(max_length=20, verbose_name='Статус бронирования')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Итоговая стоимость')),
                ('guest_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wch.guest')),
                ('hotel_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wch.hotel')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_available', models.BooleanField(verbose_name='Доступен или нет')),
                ('price_per_night', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена за ночь')),
                ('hotel_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wch.hotel')),
                ('room_type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wch.room_type')),
            ],
        ),
    ]
