# Generated by Django 5.2.8 on 2025-11-19 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wch', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='img',
            field=models.ImageField(default='', upload_to='wch_imgs/', verbose_name='Фото'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='img',
            field=models.ImageField(default='', upload_to='wch_imgs/', verbose_name='Фото'),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='img',
            field=models.ImageField(default='', upload_to='wch_imgs/', verbose_name='Фото'),
        ),
    ]
