# Generated by Django 5.2.7 on 2025-10-08 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wch', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('В процессе', 'В процессе'), ('Забронирован', 'Забронирован')], max_length=20, verbose_name='Статус бронирования'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='phone_number',
            field=models.CharField(max_length=15, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='room',
            name='is_available',
            field=models.CharField(verbose_name='Доступен или нет'),
        ),
    ]
