# Generated by Django 5.2.7 on 2025-10-08 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wch', '0002_alter_booking_status_alter_guest_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='passport_number',
            field=models.CharField(max_length=20, verbose_name='Номер паспорта'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='phone_number',
            field=models.CharField(max_length=20, verbose_name='Номер телефона'),
        ),
    ]
